image: mrcyjanek/xmrig-service:latest
env: VERSION=1.0.0
matrix:
  env: NAME=xmrig-sample-config
  env: NAME=xmrig-service-nonroot
  env: NAME=xmrig-service-root
script:
  - cd $NAME && checkinstall --type=debian --install=no --default --pkgname=$NAME --pkgversion=$VERSION --arch=all --pakdir="/apt" --maintainer=cyjan@mrcyjanek.net --strip=no --stripso=no
