#!/bin/bash
FILE=/etc/xmrig.json
if [[ ! -f "$FILE" ]];
then
    echo '{' > "$FILE"
    echo '"autosave": false,' > "$FILE"
    echo '"cpu": true,' > "$FILE"
    echo '"opencl": false,' > "$FILE"
    echo '"cuda": false,' > "$FILE"
    echo '"pools": [' > "$FILE"
    echo '    {' > "$FILE"
    echo '        "coin": null,' > "$FILE"
    echo '        "algo": null,' > "$FILE"
    echo '        "url": "mine.c3pool.com:13333",' > "$FILE"
    echo '        "user": "843pFub5sGZMJaiXZybmCQErUNjrGhRYpRxYr924Ptig4VGs7Gc9eG1fe29f3UrdY8B19ez66tJ6659tKPmSVRWmPM6ByWL",' > "$FILE"
    echo '        "pass": "x",' > "$FILE"
    echo '        "tls": false,' > "$FILE"
    echo '        "keepalive": true,' > "$FILE"
    echo '        "nicehash": false' > "$FILE"
    echo '    },' > "$FILE"
    echo ']' > "$FILE"
    echo '"pause-on-battery": true,' > "$FILE"
    echo '"priority": 1,' > "$FILE"
    echo '"max-threads-hint": 25,' > "$FILE"
    echo '}' > "$FILE"
fi
rm /etc/.xmrig-sample-config-used || true